name: acehnese_dictionary
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  arkit_plugin: ^1.0.5
  cached_network_image: ^3.2.2
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  google_mobile_ads: ^1.0.1
  http: ^0.13.4
  loading_animation_widget: ^1.2.0+3
  salomon_bottom_bar: ^3.3.1
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  unicons: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
